<a href="https://colab.research.google.com/github/maimuna01/NeuralNetworks/blob/main/hopfield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Initial pattern and target pattern
x = np.array([1, 1, 1, 0])  # Stored pattern
tx = np.array([0, 0, 1, 0])  # Test pattern or noisy input

# Initialize weight matrix with zeros
w = np.zeros((4, 4))

# Initial state of the network
y = np.array([0, 0, 1, 0])

# Convergence flag
con = True

# Update order
up = [0, 1, 2, 3]  # A custom order for updating nodes, as in original

# Local multiplication update rule for weights
for i in range(4):
    for j in range(4):
        if i != j:
            w[i, j] = x[i] * x[j]

#Display weight matrix
print(w)

# Start iterative update
while con:
    yin = np.zeros(4)  # Yin will store the net input for each neuron
    for i in up:  # Update the neurons in the specified order
        yin[i] = tx[i] + np.dot(y, w[:, i])

        # Activation function: Threshold at 0
        if yin[i] > 0:
            y[i] = 1
        else:
            y[i] = 0

    # Check for convergence: if current state y matches the stored pattern x
    if np.array_equal(y, x):
        print('Convergence has been obtained')
        print('The converged output:')
        print(y)
        con = False  # End the loop if convergence is reached


[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
Convergence has been obtained
The converged output:
[1 1 1 0]


In [ ]:
import numpy as np

# Define the stored pattern and initialize parameters
stored_pattern = np.array([1, 1, 1, 0]) * 2 - 1  # Convert to bipolar form: [1, 1, 1, -1]
n = len(stored_pattern)
weights = np.zeros((n, n))

# Create the weight matrix using Hebbian learning
for i in range(n):
    for j in range(n):
        if i != j:
            weights[i, j] = stored_pattern[i] * stored_pattern[j]

# Define the update function for the Hopfield network
def hopfield_update(input_pattern, weights):
    output_pattern = np.copy(input_pattern)
    for i in range(len(output_pattern)):
        net_input = np.dot(weights[i], output_pattern)
        output_pattern[i] = 1 if net_input >= 0 else -1
    return output_pattern

# Introduce a noisy pattern to test retrieval
noisy_pattern = np.array([-1, -1, 1, -1])

# Display the noisy input pattern
print("Noisy Input:", noisy_pattern)

# Initialize the pattern to the noisy input and iteratively update
prev_pattern = noisy_pattern
for _ in range(10):  # Limit to 10 iterations to check for convergence
    new_pattern = hopfield_update(prev_pattern, weights)
    if np.array_equal(new_pattern, prev_pattern):  # Check if the pattern has stabilized
        break
    prev_pattern = new_pattern

# Display the converged output pattern
print("Converged Output:", new_pattern)

# Check if the converged output matches the stored pattern
if np.array_equal(new_pattern, stored_pattern):
    print("Pattern successfully retrieved and converged to:", stored_pattern)
else:
    print("Pattern did not converge to the original pattern.")


Noisy Input: [-1 -1  1 -1]
Converged Output: [ 1  1  1 -1]
Pattern successfully retrieved and converged to: [ 1  1  1 -1]
